### ISSUE TITLE
Not working well with gnome 3.20

### ISSUE THREAD

**Issue by xxxifan** [franziskuskiefer/app-keys-gnome-shell-extension#28]
I found that it just won't work sometimes when I want to run nautilus. other keys just working fine but nautilus has no response. If I re-enable appkeys in tweak tool it just back to life, but after, again no response.

**Comment by franziskuskiefer** [comment]
Do you have a stack trace or something? I didn't run into any problems yet. Maybe it's some interaction with another extension?

**Comment by xxxifan** [comment]
sorry I don't know how to get a stack trace, can you tell me ? It's almost happens on my all PCs

**Comment by franglais125** [comment]
@xxxifan :

This may be a combination of 2 things:
1) Nautilus can be a bit special, due to drawing icons on the desktop (do you have that enabled?)
2) When the app-keys stop working, is it randomly, or after the screen is locked (or you suspend the computer)? What other extensions do you use?

Also, you can sometimes get extra information from `/var/log/user.log`!

**Comment by franziskuskiefer** [comment]
@xxxifan is this still an issue or did #31 fix this?

**Comment by xxxifan** [comment]
It almost working after I use github version, so I think it did fix the issue.

**Comment by franziskuskiefer** [comment]
I'll close this then. Please file a new issue if you run into the problem again
